# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 16254fab5eac22dd1bf46b971c43460805cb6fa3  # frozen: v1.45.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
