# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: d032af694c17201cfcbd4d5ac106dd37926d39f9  # frozen: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
